name: Build and Test

on:
  push:
    branches:
      - main
      - mohadeseh-alipour-patch-1
  pull_request:
    branches:
      - main
      - mohadeseh-alipour-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
